// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeployQueueParams creates a new DeployQueueParams object
// with the default values initialized.
func NewDeployQueueParams() *DeployQueueParams {

	return &DeployQueueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeployQueueParamsWithTimeout creates a new DeployQueueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeployQueueParamsWithTimeout(timeout time.Duration) *DeployQueueParams {

	return &DeployQueueParams{

		timeout: timeout,
	}
}

// NewDeployQueueParamsWithContext creates a new DeployQueueParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeployQueueParamsWithContext(ctx context.Context) *DeployQueueParams {

	return &DeployQueueParams{

		Context: ctx,
	}
}

// NewDeployQueueParamsWithHTTPClient creates a new DeployQueueParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeployQueueParamsWithHTTPClient(client *http.Client) *DeployQueueParams {

	return &DeployQueueParams{
		HTTPClient: client,
	}
}

/*DeployQueueParams contains all the parameters to send to the API endpoint
for the deploy queue operation typically these are written to a http.Request
*/
type DeployQueueParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the deploy queue params
func (o *DeployQueueParams) WithTimeout(timeout time.Duration) *DeployQueueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deploy queue params
func (o *DeployQueueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deploy queue params
func (o *DeployQueueParams) WithContext(ctx context.Context) *DeployQueueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deploy queue params
func (o *DeployQueueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deploy queue params
func (o *DeployQueueParams) WithHTTPClient(client *http.Client) *DeployQueueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deploy queue params
func (o *DeployQueueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeployQueueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
