// Code generated by go-swagger; DO NOT EDIT.

package autoscaler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateAutoscalerCountReader is a Reader for the UpdateAutoscalerCount structure.
type UpdateAutoscalerCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAutoscalerCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewUpdateAutoscalerCountAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUpdateAutoscalerCountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateAutoscalerCountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateAutoscalerCountAccepted creates a UpdateAutoscalerCountAccepted with default headers values
func NewUpdateAutoscalerCountAccepted() *UpdateAutoscalerCountAccepted {
	return &UpdateAutoscalerCountAccepted{}
}

/*UpdateAutoscalerCountAccepted handles this case with default header values.

Set desired instance count for a service instance
*/
type UpdateAutoscalerCountAccepted struct {
	Payload *UpdateAutoscalerCountAcceptedBody
}

func (o *UpdateAutoscalerCountAccepted) Error() string {
	return fmt.Sprintf("[POST /services/{service}/{instance}/autoscaler][%d] updateAutoscalerCountAccepted  %+v", 202, o.Payload)
}

func (o *UpdateAutoscalerCountAccepted) GetPayload() *UpdateAutoscalerCountAcceptedBody {
	return o.Payload
}

func (o *UpdateAutoscalerCountAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateAutoscalerCountAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAutoscalerCountNotFound creates a UpdateAutoscalerCountNotFound with default headers values
func NewUpdateAutoscalerCountNotFound() *UpdateAutoscalerCountNotFound {
	return &UpdateAutoscalerCountNotFound{}
}

/*UpdateAutoscalerCountNotFound handles this case with default header values.

Deployment key not found
*/
type UpdateAutoscalerCountNotFound struct {
}

func (o *UpdateAutoscalerCountNotFound) Error() string {
	return fmt.Sprintf("[POST /services/{service}/{instance}/autoscaler][%d] updateAutoscalerCountNotFound ", 404)
}

func (o *UpdateAutoscalerCountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateAutoscalerCountInternalServerError creates a UpdateAutoscalerCountInternalServerError with default headers values
func NewUpdateAutoscalerCountInternalServerError() *UpdateAutoscalerCountInternalServerError {
	return &UpdateAutoscalerCountInternalServerError{}
}

/*UpdateAutoscalerCountInternalServerError handles this case with default header values.

Instance failure
*/
type UpdateAutoscalerCountInternalServerError struct {
}

func (o *UpdateAutoscalerCountInternalServerError) Error() string {
	return fmt.Sprintf("[POST /services/{service}/{instance}/autoscaler][%d] updateAutoscalerCountInternalServerError ", 500)
}

func (o *UpdateAutoscalerCountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*UpdateAutoscalerCountAcceptedBody update autoscaler count accepted body
swagger:model UpdateAutoscalerCountAcceptedBody
*/
type UpdateAutoscalerCountAcceptedBody struct {

	// desired instances
	DesiredInstances int64 `json:"desired_instances,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this update autoscaler count accepted body
func (o *UpdateAutoscalerCountAcceptedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateAutoscalerCountAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateAutoscalerCountAcceptedBody) UnmarshalBinary(b []byte) error {
	var res UpdateAutoscalerCountAcceptedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateAutoscalerCountBody update autoscaler count body
swagger:model UpdateAutoscalerCountBody
*/
type UpdateAutoscalerCountBody struct {

	// calculated instances
	CalculatedInstances int64 `json:"calculated_instances,omitempty"`

	// desired instances
	DesiredInstances int64 `json:"desired_instances,omitempty"`
}

// Validate validates this update autoscaler count body
func (o *UpdateAutoscalerCountBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateAutoscalerCountBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateAutoscalerCountBody) UnmarshalBinary(b []byte) error {
	var res UpdateAutoscalerCountBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
