// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EnvoyLocation envoy location
//
// swagger:model EnvoyLocation
type EnvoyLocation struct {

	// Envoy backends running in this location
	Backends []*EnvoyBackend `json:"backends"`

	// Whether this backend is proxied through Casper
	IsProxiedThroughCasper bool `json:"is_proxied_through_casper,omitempty"`

	// Name of the location
	Name string `json:"name,omitempty"`

	// Number of running backends for the service in this location
	RunningBackendsCount int32 `json:"running_backends_count,omitempty"`
}

// Validate validates this envoy location
func (m *EnvoyLocation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBackends(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EnvoyLocation) validateBackends(formats strfmt.Registry) error {

	if swag.IsZero(m.Backends) { // not required
		return nil
	}

	for i := 0; i < len(m.Backends); i++ {
		if swag.IsZero(m.Backends[i]) { // not required
			continue
		}

		if m.Backends[i] != nil {
			if err := m.Backends[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("backends" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EnvoyLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnvoyLocation) UnmarshalBinary(b []byte) error {
	var res EnvoyLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
