// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteServiceAutoscalerPauseReader is a Reader for the DeleteServiceAutoscalerPause structure.
type DeleteServiceAutoscalerPauseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceAutoscalerPauseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteServiceAutoscalerPauseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteServiceAutoscalerPauseInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteServiceAutoscalerPauseOK creates a DeleteServiceAutoscalerPauseOK with default headers values
func NewDeleteServiceAutoscalerPauseOK() *DeleteServiceAutoscalerPauseOK {
	return &DeleteServiceAutoscalerPauseOK{}
}

/*DeleteServiceAutoscalerPauseOK handles this case with default header values.

Service autoscaler successfully unpaused
*/
type DeleteServiceAutoscalerPauseOK struct {
}

func (o *DeleteServiceAutoscalerPauseOK) Error() string {
	return fmt.Sprintf("[DELETE /service_autoscaler/pause][%d] deleteServiceAutoscalerPauseOK ", 200)
}

func (o *DeleteServiceAutoscalerPauseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServiceAutoscalerPauseInternalServerError creates a DeleteServiceAutoscalerPauseInternalServerError with default headers values
func NewDeleteServiceAutoscalerPauseInternalServerError() *DeleteServiceAutoscalerPauseInternalServerError {
	return &DeleteServiceAutoscalerPauseInternalServerError{}
}

/*DeleteServiceAutoscalerPauseInternalServerError handles this case with default header values.

Unable to talk to zookeeper
*/
type DeleteServiceAutoscalerPauseInternalServerError struct {
}

func (o *DeleteServiceAutoscalerPauseInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /service_autoscaler/pause][%d] deleteServiceAutoscalerPauseInternalServerError ", 500)
}

func (o *DeleteServiceAutoscalerPauseInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
