// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteServiceAutoscalerPauseParams creates a new DeleteServiceAutoscalerPauseParams object
// with the default values initialized.
func NewDeleteServiceAutoscalerPauseParams() *DeleteServiceAutoscalerPauseParams {

	return &DeleteServiceAutoscalerPauseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceAutoscalerPauseParamsWithTimeout creates a new DeleteServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteServiceAutoscalerPauseParamsWithTimeout(timeout time.Duration) *DeleteServiceAutoscalerPauseParams {

	return &DeleteServiceAutoscalerPauseParams{

		timeout: timeout,
	}
}

// NewDeleteServiceAutoscalerPauseParamsWithContext creates a new DeleteServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteServiceAutoscalerPauseParamsWithContext(ctx context.Context) *DeleteServiceAutoscalerPauseParams {

	return &DeleteServiceAutoscalerPauseParams{

		Context: ctx,
	}
}

// NewDeleteServiceAutoscalerPauseParamsWithHTTPClient creates a new DeleteServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteServiceAutoscalerPauseParamsWithHTTPClient(client *http.Client) *DeleteServiceAutoscalerPauseParams {

	return &DeleteServiceAutoscalerPauseParams{
		HTTPClient: client,
	}
}

/*DeleteServiceAutoscalerPauseParams contains all the parameters to send to the API endpoint
for the delete service autoscaler pause operation typically these are written to a http.Request
*/
type DeleteServiceAutoscalerPauseParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete service autoscaler pause params
func (o *DeleteServiceAutoscalerPauseParams) WithTimeout(timeout time.Duration) *DeleteServiceAutoscalerPauseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service autoscaler pause params
func (o *DeleteServiceAutoscalerPauseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service autoscaler pause params
func (o *DeleteServiceAutoscalerPauseParams) WithContext(ctx context.Context) *DeleteServiceAutoscalerPauseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service autoscaler pause params
func (o *DeleteServiceAutoscalerPauseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete service autoscaler pause params
func (o *DeleteServiceAutoscalerPauseParams) WithHTTPClient(client *http.Client) *DeleteServiceAutoscalerPauseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete service autoscaler pause params
func (o *DeleteServiceAutoscalerPauseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceAutoscalerPauseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
