// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServiceAutoscalerPauseParams creates a new GetServiceAutoscalerPauseParams object
// with the default values initialized.
func NewGetServiceAutoscalerPauseParams() *GetServiceAutoscalerPauseParams {

	return &GetServiceAutoscalerPauseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceAutoscalerPauseParamsWithTimeout creates a new GetServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServiceAutoscalerPauseParamsWithTimeout(timeout time.Duration) *GetServiceAutoscalerPauseParams {

	return &GetServiceAutoscalerPauseParams{

		timeout: timeout,
	}
}

// NewGetServiceAutoscalerPauseParamsWithContext creates a new GetServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServiceAutoscalerPauseParamsWithContext(ctx context.Context) *GetServiceAutoscalerPauseParams {

	return &GetServiceAutoscalerPauseParams{

		Context: ctx,
	}
}

// NewGetServiceAutoscalerPauseParamsWithHTTPClient creates a new GetServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServiceAutoscalerPauseParamsWithHTTPClient(client *http.Client) *GetServiceAutoscalerPauseParams {

	return &GetServiceAutoscalerPauseParams{
		HTTPClient: client,
	}
}

/*GetServiceAutoscalerPauseParams contains all the parameters to send to the API endpoint
for the get service autoscaler pause operation typically these are written to a http.Request
*/
type GetServiceAutoscalerPauseParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get service autoscaler pause params
func (o *GetServiceAutoscalerPauseParams) WithTimeout(timeout time.Duration) *GetServiceAutoscalerPauseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service autoscaler pause params
func (o *GetServiceAutoscalerPauseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service autoscaler pause params
func (o *GetServiceAutoscalerPauseParams) WithContext(ctx context.Context) *GetServiceAutoscalerPauseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service autoscaler pause params
func (o *GetServiceAutoscalerPauseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service autoscaler pause params
func (o *GetServiceAutoscalerPauseParams) WithHTTPClient(client *http.Client) *GetServiceAutoscalerPauseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service autoscaler pause params
func (o *GetServiceAutoscalerPauseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceAutoscalerPauseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
