// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetServiceAutoscalerPauseReader is a Reader for the GetServiceAutoscalerPause structure.
type GetServiceAutoscalerPauseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServiceAutoscalerPauseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServiceAutoscalerPauseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetServiceAutoscalerPauseInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServiceAutoscalerPauseOK creates a GetServiceAutoscalerPauseOK with default headers values
func NewGetServiceAutoscalerPauseOK() *GetServiceAutoscalerPauseOK {
	return &GetServiceAutoscalerPauseOK{}
}

/*GetServiceAutoscalerPauseOK handles this case with default header values.

The time until which the servcie autoscaler is paused for
*/
type GetServiceAutoscalerPauseOK struct {
	Payload string
}

func (o *GetServiceAutoscalerPauseOK) Error() string {
	return fmt.Sprintf("[GET /service_autoscaler/pause][%d] getServiceAutoscalerPauseOK  %+v", 200, o.Payload)
}

func (o *GetServiceAutoscalerPauseOK) GetPayload() string {
	return o.Payload
}

func (o *GetServiceAutoscalerPauseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServiceAutoscalerPauseInternalServerError creates a GetServiceAutoscalerPauseInternalServerError with default headers values
func NewGetServiceAutoscalerPauseInternalServerError() *GetServiceAutoscalerPauseInternalServerError {
	return &GetServiceAutoscalerPauseInternalServerError{}
}

/*GetServiceAutoscalerPauseInternalServerError handles this case with default header values.

Unable to talk to zookeeper
*/
type GetServiceAutoscalerPauseInternalServerError struct {
}

func (o *GetServiceAutoscalerPauseInternalServerError) Error() string {
	return fmt.Sprintf("[GET /service_autoscaler/pause][%d] getServiceAutoscalerPauseInternalServerError ", 500)
}

func (o *GetServiceAutoscalerPauseInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
