// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ShowVersionReader is a Reader for the ShowVersion structure.
type ShowVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewShowVersionOK creates a ShowVersionOK with default headers values
func NewShowVersionOK() *ShowVersionOK {
	return &ShowVersionOK{}
}

/*ShowVersionOK handles this case with default header values.

Version of paasta_tools package
*/
type ShowVersionOK struct {
	Payload string
}

func (o *ShowVersionOK) Error() string {
	return fmt.Sprintf("[GET /version][%d] showVersionOK  %+v", 200, o.Payload)
}

func (o *ShowVersionOK) GetPayload() string {
	return o.Payload
}

func (o *ShowVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
