// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateServiceAutoscalerPauseReader is a Reader for the UpdateServiceAutoscalerPause structure.
type UpdateServiceAutoscalerPauseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateServiceAutoscalerPauseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateServiceAutoscalerPauseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewUpdateServiceAutoscalerPauseInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateServiceAutoscalerPauseOK creates a UpdateServiceAutoscalerPauseOK with default headers values
func NewUpdateServiceAutoscalerPauseOK() *UpdateServiceAutoscalerPauseOK {
	return &UpdateServiceAutoscalerPauseOK{}
}

/*UpdateServiceAutoscalerPauseOK handles this case with default header values.

Service autoscaler successfully paused
*/
type UpdateServiceAutoscalerPauseOK struct {
}

func (o *UpdateServiceAutoscalerPauseOK) Error() string {
	return fmt.Sprintf("[POST /service_autoscaler/pause][%d] updateServiceAutoscalerPauseOK ", 200)
}

func (o *UpdateServiceAutoscalerPauseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceAutoscalerPauseInternalServerError creates a UpdateServiceAutoscalerPauseInternalServerError with default headers values
func NewUpdateServiceAutoscalerPauseInternalServerError() *UpdateServiceAutoscalerPauseInternalServerError {
	return &UpdateServiceAutoscalerPauseInternalServerError{}
}

/*UpdateServiceAutoscalerPauseInternalServerError handles this case with default header values.

Unable to talk to zookeeper
*/
type UpdateServiceAutoscalerPauseInternalServerError struct {
}

func (o *UpdateServiceAutoscalerPauseInternalServerError) Error() string {
	return fmt.Sprintf("[POST /service_autoscaler/pause][%d] updateServiceAutoscalerPauseInternalServerError ", 500)
}

func (o *UpdateServiceAutoscalerPauseInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*UpdateServiceAutoscalerPauseBody update service autoscaler pause body
swagger:model UpdateServiceAutoscalerPauseBody
*/
type UpdateServiceAutoscalerPauseBody struct {

	// minutes
	Minutes int64 `json:"minutes,omitempty"`
}

// Validate validates this update service autoscaler pause body
func (o *UpdateServiceAutoscalerPauseBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateServiceAutoscalerPauseBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateServiceAutoscalerPauseBody) UnmarshalBinary(b []byte) error {
	var res UpdateServiceAutoscalerPauseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
