// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateServiceAutoscalerPauseParams creates a new UpdateServiceAutoscalerPauseParams object
// with the default values initialized.
func NewUpdateServiceAutoscalerPauseParams() *UpdateServiceAutoscalerPauseParams {
	var ()
	return &UpdateServiceAutoscalerPauseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateServiceAutoscalerPauseParamsWithTimeout creates a new UpdateServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateServiceAutoscalerPauseParamsWithTimeout(timeout time.Duration) *UpdateServiceAutoscalerPauseParams {
	var ()
	return &UpdateServiceAutoscalerPauseParams{

		timeout: timeout,
	}
}

// NewUpdateServiceAutoscalerPauseParamsWithContext creates a new UpdateServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateServiceAutoscalerPauseParamsWithContext(ctx context.Context) *UpdateServiceAutoscalerPauseParams {
	var ()
	return &UpdateServiceAutoscalerPauseParams{

		Context: ctx,
	}
}

// NewUpdateServiceAutoscalerPauseParamsWithHTTPClient creates a new UpdateServiceAutoscalerPauseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateServiceAutoscalerPauseParamsWithHTTPClient(client *http.Client) *UpdateServiceAutoscalerPauseParams {
	var ()
	return &UpdateServiceAutoscalerPauseParams{
		HTTPClient: client,
	}
}

/*UpdateServiceAutoscalerPauseParams contains all the parameters to send to the API endpoint
for the update service autoscaler pause operation typically these are written to a http.Request
*/
type UpdateServiceAutoscalerPauseParams struct {

	/*JSONBody*/
	JSONBody UpdateServiceAutoscalerPauseBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) WithTimeout(timeout time.Duration) *UpdateServiceAutoscalerPauseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) WithContext(ctx context.Context) *UpdateServiceAutoscalerPauseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) WithHTTPClient(client *http.Client) *UpdateServiceAutoscalerPauseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) WithJSONBody(jSONBody UpdateServiceAutoscalerPauseBody) *UpdateServiceAutoscalerPauseParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the update service autoscaler pause params
func (o *UpdateServiceAutoscalerPauseParams) SetJSONBody(jSONBody UpdateServiceAutoscalerPauseBody) {
	o.JSONBody = jSONBody
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateServiceAutoscalerPauseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.JSONBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
