// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTaskInstanceParams creates a new TaskInstanceParams object
// with the default values initialized.
func NewTaskInstanceParams() *TaskInstanceParams {
	var ()
	return &TaskInstanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTaskInstanceParamsWithTimeout creates a new TaskInstanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTaskInstanceParamsWithTimeout(timeout time.Duration) *TaskInstanceParams {
	var ()
	return &TaskInstanceParams{

		timeout: timeout,
	}
}

// NewTaskInstanceParamsWithContext creates a new TaskInstanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewTaskInstanceParamsWithContext(ctx context.Context) *TaskInstanceParams {
	var ()
	return &TaskInstanceParams{

		Context: ctx,
	}
}

// NewTaskInstanceParamsWithHTTPClient creates a new TaskInstanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTaskInstanceParamsWithHTTPClient(client *http.Client) *TaskInstanceParams {
	var ()
	return &TaskInstanceParams{
		HTTPClient: client,
	}
}

/*TaskInstanceParams contains all the parameters to send to the API endpoint
for the task instance operation typically these are written to a http.Request
*/
type TaskInstanceParams struct {

	/*Instance
	  Instance name

	*/
	Instance string
	/*Service
	  Service name

	*/
	Service string
	/*TaskID
	  mesos task id

	*/
	TaskID string
	/*Verbose
	  Return slave and executor for task

	*/
	Verbose *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the task instance params
func (o *TaskInstanceParams) WithTimeout(timeout time.Duration) *TaskInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the task instance params
func (o *TaskInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the task instance params
func (o *TaskInstanceParams) WithContext(ctx context.Context) *TaskInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the task instance params
func (o *TaskInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the task instance params
func (o *TaskInstanceParams) WithHTTPClient(client *http.Client) *TaskInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the task instance params
func (o *TaskInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstance adds the instance to the task instance params
func (o *TaskInstanceParams) WithInstance(instance string) *TaskInstanceParams {
	o.SetInstance(instance)
	return o
}

// SetInstance adds the instance to the task instance params
func (o *TaskInstanceParams) SetInstance(instance string) {
	o.Instance = instance
}

// WithService adds the service to the task instance params
func (o *TaskInstanceParams) WithService(service string) *TaskInstanceParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the task instance params
func (o *TaskInstanceParams) SetService(service string) {
	o.Service = service
}

// WithTaskID adds the taskID to the task instance params
func (o *TaskInstanceParams) WithTaskID(taskID string) *TaskInstanceParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the task instance params
func (o *TaskInstanceParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WithVerbose adds the verbose to the task instance params
func (o *TaskInstanceParams) WithVerbose(verbose *bool) *TaskInstanceParams {
	o.SetVerbose(verbose)
	return o
}

// SetVerbose adds the verbose to the task instance params
func (o *TaskInstanceParams) SetVerbose(verbose *bool) {
	o.Verbose = verbose
}

// WriteToRequest writes these params to a swagger request
func (o *TaskInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instance
	if err := r.SetPathParam("instance", o.Instance); err != nil {
		return err
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	// path param task_id
	if err := r.SetPathParam("task_id", o.TaskID); err != nil {
		return err
	}

	if o.Verbose != nil {

		// query param verbose
		var qrVerbose bool
		if o.Verbose != nil {
			qrVerbose = *o.Verbose
		}
		qVerbose := swag.FormatBool(qrVerbose)
		if qVerbose != "" {
			if err := r.SetQueryParam("verbose", qVerbose); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
