// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/Yelp/paasta-tools-go/pkg/paasta_api/models"
)

// TasksInstanceReader is a Reader for the TasksInstance structure.
type TasksInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TasksInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTasksInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTasksInstanceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTasksInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTasksInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTasksInstanceOK creates a TasksInstanceOK with default headers values
func NewTasksInstanceOK() *TasksInstanceOK {
	return &TasksInstanceOK{}
}

/*TasksInstanceOK handles this case with default header values.

List of tasks associated with an instance
*/
type TasksInstanceOK struct {
	Payload models.InstanceTasks
}

func (o *TasksInstanceOK) Error() string {
	return fmt.Sprintf("[GET /services/{service}/{instance}/tasks][%d] tasksInstanceOK  %+v", 200, o.Payload)
}

func (o *TasksInstanceOK) GetPayload() models.InstanceTasks {
	return o.Payload
}

func (o *TasksInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTasksInstanceBadRequest creates a TasksInstanceBadRequest with default headers values
func NewTasksInstanceBadRequest() *TasksInstanceBadRequest {
	return &TasksInstanceBadRequest{}
}

/*TasksInstanceBadRequest handles this case with default header values.

Bad request
*/
type TasksInstanceBadRequest struct {
}

func (o *TasksInstanceBadRequest) Error() string {
	return fmt.Sprintf("[GET /services/{service}/{instance}/tasks][%d] tasksInstanceBadRequest ", 400)
}

func (o *TasksInstanceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTasksInstanceNotFound creates a TasksInstanceNotFound with default headers values
func NewTasksInstanceNotFound() *TasksInstanceNotFound {
	return &TasksInstanceNotFound{}
}

/*TasksInstanceNotFound handles this case with default header values.

Deployment key not found
*/
type TasksInstanceNotFound struct {
}

func (o *TasksInstanceNotFound) Error() string {
	return fmt.Sprintf("[GET /services/{service}/{instance}/tasks][%d] tasksInstanceNotFound ", 404)
}

func (o *TasksInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTasksInstanceInternalServerError creates a TasksInstanceInternalServerError with default headers values
func NewTasksInstanceInternalServerError() *TasksInstanceInternalServerError {
	return &TasksInstanceInternalServerError{}
}

/*TasksInstanceInternalServerError handles this case with default header values.

Instance failure
*/
type TasksInstanceInternalServerError struct {
}

func (o *TasksInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[GET /services/{service}/{instance}/tasks][%d] tasksInstanceInternalServerError ", 500)
}

func (o *TasksInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
