// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AdhocLaunchHistory A single run
// swagger:model AdhocLaunchHistory
type AdhocLaunchHistory struct {

	// framework id
	FrameworkID string `json:"framework_id,omitempty"`

	// when the job was launched
	LaunchTime string `json:"launch_time,omitempty"`

	// id of the single run
	RunID string `json:"run_id,omitempty"`
}

// Validate validates this adhoc launch history
func (m *AdhocLaunchHistory) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdhocLaunchHistory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdhocLaunchHistory) UnmarshalBinary(b []byte) error {
	var res AdhocLaunchHistory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
