// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeployQueue Current state of the deployd queue
//
// swagger:model DeployQueue
type DeployQueue struct {

	// Service instances that are ready to be acted on by deployd
	AvailableServiceInstances []*DeployQueueServiceInstance `json:"available_service_instances"`

	// Service instances that deployd is waiting to act on
	UnavailableServiceInstances []*DeployQueueServiceInstance `json:"unavailable_service_instances"`
}

// Validate validates this deploy queue
func (m *DeployQueue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvailableServiceInstances(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnavailableServiceInstances(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeployQueue) validateAvailableServiceInstances(formats strfmt.Registry) error {

	if swag.IsZero(m.AvailableServiceInstances) { // not required
		return nil
	}

	for i := 0; i < len(m.AvailableServiceInstances); i++ {
		if swag.IsZero(m.AvailableServiceInstances[i]) { // not required
			continue
		}

		if m.AvailableServiceInstances[i] != nil {
			if err := m.AvailableServiceInstances[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("available_service_instances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeployQueue) validateUnavailableServiceInstances(formats strfmt.Registry) error {

	if swag.IsZero(m.UnavailableServiceInstances) { // not required
		return nil
	}

	for i := 0; i < len(m.UnavailableServiceInstances); i++ {
		if swag.IsZero(m.UnavailableServiceInstances[i]) { // not required
			continue
		}

		if m.UnavailableServiceInstances[i] != nil {
			if err := m.UnavailableServiceInstances[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("unavailable_service_instances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeployQueue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeployQueue) UnmarshalBinary(b []byte) error {
	var res DeployQueue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
