// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EnvoyBackend envoy backend
//
// swagger:model EnvoyBackend
type EnvoyBackend struct {

	// Address of the host on which the backend is running
	Address string `json:"address,omitempty"`

	// Status of the backend in Envoy as reported by the EDS
	EdsHealthStatus string `json:"eds_health_status,omitempty"`

	// Whether this backend has an associated task running
	HasAssociatedTask bool `json:"has_associated_task,omitempty"`

	// Name of the host on which the backend is running
	Hostname string `json:"hostname,omitempty"`

	// Port number on which the backend responds
	PortValue int32 `json:"port_value,omitempty"`

	// The weight of this backend in the cluster
	Weight int32 `json:"weight,omitempty"`
}

// Validate validates this envoy backend
func (m *EnvoyBackend) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EnvoyBackend) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnvoyBackend) UnmarshalBinary(b []byte) error {
	var res EnvoyBackend
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
