// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FloatAndError float and error
// swagger:model FloatAndError
type FloatAndError struct {

	// error message
	ErrorMessage string `json:"error_message,omitempty"`

	// value
	Value float32 `json:"value,omitempty"`
}

// Validate validates this float and error
func (m *FloatAndError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FloatAndError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FloatAndError) UnmarshalBinary(b []byte) error {
	var res FloatAndError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
