// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HPAMetric h p a metric
//
// swagger:model HPAMetric
type HPAMetric struct {

	// setpoint/target_value as specified in yelpsoa_configs
	CurrentValue string `json:"current_value,omitempty"`

	// name of the metric
	Name string `json:"name,omitempty"`

	// setpoint/target_value as specified in yelpsoa_configs
	TargetValue string `json:"target_value,omitempty"`
}

// Validate validates this h p a metric
func (m *HPAMetric) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HPAMetric) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HPAMetric) UnmarshalBinary(b []byte) error {
	var res HPAMetric
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
