// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IntegerAndError integer and error
// swagger:model IntegerAndError
type IntegerAndError struct {

	// error message
	ErrorMessage string `json:"error_message,omitempty"`

	// value
	Value int32 `json:"value,omitempty"`
}

// Validate validates this integer and error
func (m *IntegerAndError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IntegerAndError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IntegerAndError) UnmarshalBinary(b []byte) error {
	var res IntegerAndError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
