// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MarathonAutoscalingInfo marathon autoscaling info
// swagger:model MarathonAutoscalingInfo
type MarathonAutoscalingInfo struct {

	// The number of instances of the service currently running
	CurrentInstances int32 `json:"current_instances,omitempty"`

	// The current utilization of the instances' allocated resources
	CurrentUtilization float32 `json:"current_utilization,omitempty"`

	// The maximum number of instances that the autoscaler will scale to
	MaxInstances int32 `json:"max_instances,omitempty"`

	// The minimum number of instances that the autoscaler will scale to
	MinInstances int32 `json:"min_instances,omitempty"`

	// The autoscaler's current target number of instances of this service to run
	TargetInstances int32 `json:"target_instances,omitempty"`
}

// Validate validates this marathon autoscaling info
func (m *MarathonAutoscalingInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarathonAutoscalingInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarathonAutoscalingInfo) UnmarshalBinary(b []byte) error {
	var res MarathonAutoscalingInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
