// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MarathonTask marathon task
// swagger:model MarathonTask
type MarathonTask struct {

	// Time at which the task was deployed
	DeployedTimestamp float32 `json:"deployed_timestamp,omitempty"`

	// Name of the host on which the task is running
	Host string `json:"host,omitempty"`

	// ID of the task in Mesos
	ID string `json:"id,omitempty"`

	// Whether Marathon thinks the task is healthy
	IsHealthy bool `json:"is_healthy,omitempty"`

	// Port on which the task is listening
	Port int32 `json:"port,omitempty"`
}

// Validate validates this marathon task
func (m *MarathonTask) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarathonTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarathonTask) UnmarshalBinary(b []byte) error {
	var res MarathonTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
