// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MarathonMesosStatus marathon mesos status
// swagger:model MarathonMesosStatus
type MarathonMesosStatus struct {

	// Error message when Mesos tasks cannot be queried
	ErrorMessage string `json:"error_message,omitempty"`

	// Non-running tasks associated to this service
	NonRunningTasks []*MarathonMesosNonrunningTask `json:"non_running_tasks"`

	// The number of running Mesos tasks associated to this service
	RunningTaskCount int32 `json:"running_task_count,omitempty"`

	// Currently running tasks associated to this service
	RunningTasks []*MarathonMesosRunningTask `json:"running_tasks"`
}

// Validate validates this marathon mesos status
func (m *MarathonMesosStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNonRunningTasks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRunningTasks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MarathonMesosStatus) validateNonRunningTasks(formats strfmt.Registry) error {

	if swag.IsZero(m.NonRunningTasks) { // not required
		return nil
	}

	for i := 0; i < len(m.NonRunningTasks); i++ {
		if swag.IsZero(m.NonRunningTasks[i]) { // not required
			continue
		}

		if m.NonRunningTasks[i] != nil {
			if err := m.NonRunningTasks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("non_running_tasks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MarathonMesosStatus) validateRunningTasks(formats strfmt.Registry) error {

	if swag.IsZero(m.RunningTasks) { // not required
		return nil
	}

	for i := 0; i < len(m.RunningTasks); i++ {
		if swag.IsZero(m.RunningTasks[i]) { // not required
			continue
		}

		if m.RunningTasks[i] != nil {
			if err := m.RunningTasks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("running_tasks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MarathonMesosStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarathonMesosStatus) UnmarshalBinary(b []byte) error {
	var res MarathonMesosStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
