// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MarathonDashboardItem Marathon service, instance, and shard url
// swagger:model MarathonDashboardItem
type MarathonDashboardItem struct {

	// Instance name
	Instance string `json:"instance,omitempty"`

	// Service name
	Service string `json:"service,omitempty"`

	// Marathon Shard URL
	ShardURL string `json:"shard_url,omitempty"`
}

// Validate validates this marathon dashboard item
func (m *MarathonDashboardItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarathonDashboardItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarathonDashboardItem) UnmarshalBinary(b []byte) error {
	var res MarathonDashboardItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
