// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ResourceValue resource value
// swagger:model ResourceValue
type ResourceValue struct {

	// free
	Free float64 `json:"free,omitempty"`

	// total
	Total float64 `json:"total,omitempty"`

	// used
	Used float64 `json:"used,omitempty"`
}

// Validate validates this resource value
func (m *ResourceValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceValue) UnmarshalBinary(b []byte) error {
	var res ResourceValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
