// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TaskTailLines task tail lines
// swagger:model TaskTailLines
type TaskTailLines struct {

	// Error message when fetching tail lines fails
	ErrorMessage string `json:"error_message,omitempty"`

	// The requested number of lines from the task's stderr
	Stderr []string `json:"stderr"`

	// The requested number of lines from the task's stdout
	Stdout []string `json:"stdout"`
}

// Validate validates this task tail lines
func (m *TaskTailLines) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskTailLines) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskTailLines) UnmarshalBinary(b []byte) error {
	var res TaskTailLines
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
