/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paastaapi

import (
	"encoding/json"
)

// InstanceStatusTron struct for InstanceStatusTron
type InstanceStatusTron struct {
	// The command of the action
	ActionCommand *string `json:"action_command,omitempty"`
	// The name of the action
	ActionName *string `json:"action_name,omitempty"`
	// The raw command of the action
	ActionRawCommand *string `json:"action_raw_command,omitempty"`
	// The start time of the action
	ActionStartTime *string `json:"action_start_time,omitempty"`
	// The state of the action
	ActionState *string `json:"action_state,omitempty"`
	// The stderr command of the action
	ActionStderr *string `json:"action_stderr,omitempty"`
	// The stdout command of the action
	ActionStdout *string `json:"action_stdout,omitempty"`
	// The name of this job
	JobName string `json:"job_name"`
	// The job schedule of the job
	JobSchedule *string `json:"job_schedule,omitempty"`
	// The status of the job
	JobStatus *string `json:"job_status,omitempty"`
	// The dashboard url of the job
	JobUrl string `json:"job_url"`
}

// NewInstanceStatusTron instantiates a new InstanceStatusTron object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceStatusTron(jobName string, jobUrl string, ) *InstanceStatusTron {
	this := InstanceStatusTron{}
	this.JobName = jobName
	this.JobUrl = jobUrl
	return &this
}

// NewInstanceStatusTronWithDefaults instantiates a new InstanceStatusTron object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceStatusTronWithDefaults() *InstanceStatusTron {
	this := InstanceStatusTron{}
	return &this
}

// GetActionCommand returns the ActionCommand field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetActionCommand() string {
	if o == nil || o.ActionCommand == nil {
		var ret string
		return ret
	}
	return *o.ActionCommand
}

// GetActionCommandOk returns a tuple with the ActionCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetActionCommandOk() (*string, bool) {
	if o == nil || o.ActionCommand == nil {
		return nil, false
	}
	return o.ActionCommand, true
}

// HasActionCommand returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasActionCommand() bool {
	if o != nil && o.ActionCommand != nil {
		return true
	}

	return false
}

// SetActionCommand gets a reference to the given string and assigns it to the ActionCommand field.
func (o *InstanceStatusTron) SetActionCommand(v string) {
	o.ActionCommand = &v
}

// GetActionName returns the ActionName field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetActionName() string {
	if o == nil || o.ActionName == nil {
		var ret string
		return ret
	}
	return *o.ActionName
}

// GetActionNameOk returns a tuple with the ActionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetActionNameOk() (*string, bool) {
	if o == nil || o.ActionName == nil {
		return nil, false
	}
	return o.ActionName, true
}

// HasActionName returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasActionName() bool {
	if o != nil && o.ActionName != nil {
		return true
	}

	return false
}

// SetActionName gets a reference to the given string and assigns it to the ActionName field.
func (o *InstanceStatusTron) SetActionName(v string) {
	o.ActionName = &v
}

// GetActionRawCommand returns the ActionRawCommand field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetActionRawCommand() string {
	if o == nil || o.ActionRawCommand == nil {
		var ret string
		return ret
	}
	return *o.ActionRawCommand
}

// GetActionRawCommandOk returns a tuple with the ActionRawCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetActionRawCommandOk() (*string, bool) {
	if o == nil || o.ActionRawCommand == nil {
		return nil, false
	}
	return o.ActionRawCommand, true
}

// HasActionRawCommand returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasActionRawCommand() bool {
	if o != nil && o.ActionRawCommand != nil {
		return true
	}

	return false
}

// SetActionRawCommand gets a reference to the given string and assigns it to the ActionRawCommand field.
func (o *InstanceStatusTron) SetActionRawCommand(v string) {
	o.ActionRawCommand = &v
}

// GetActionStartTime returns the ActionStartTime field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetActionStartTime() string {
	if o == nil || o.ActionStartTime == nil {
		var ret string
		return ret
	}
	return *o.ActionStartTime
}

// GetActionStartTimeOk returns a tuple with the ActionStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetActionStartTimeOk() (*string, bool) {
	if o == nil || o.ActionStartTime == nil {
		return nil, false
	}
	return o.ActionStartTime, true
}

// HasActionStartTime returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasActionStartTime() bool {
	if o != nil && o.ActionStartTime != nil {
		return true
	}

	return false
}

// SetActionStartTime gets a reference to the given string and assigns it to the ActionStartTime field.
func (o *InstanceStatusTron) SetActionStartTime(v string) {
	o.ActionStartTime = &v
}

// GetActionState returns the ActionState field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetActionState() string {
	if o == nil || o.ActionState == nil {
		var ret string
		return ret
	}
	return *o.ActionState
}

// GetActionStateOk returns a tuple with the ActionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetActionStateOk() (*string, bool) {
	if o == nil || o.ActionState == nil {
		return nil, false
	}
	return o.ActionState, true
}

// HasActionState returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasActionState() bool {
	if o != nil && o.ActionState != nil {
		return true
	}

	return false
}

// SetActionState gets a reference to the given string and assigns it to the ActionState field.
func (o *InstanceStatusTron) SetActionState(v string) {
	o.ActionState = &v
}

// GetActionStderr returns the ActionStderr field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetActionStderr() string {
	if o == nil || o.ActionStderr == nil {
		var ret string
		return ret
	}
	return *o.ActionStderr
}

// GetActionStderrOk returns a tuple with the ActionStderr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetActionStderrOk() (*string, bool) {
	if o == nil || o.ActionStderr == nil {
		return nil, false
	}
	return o.ActionStderr, true
}

// HasActionStderr returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasActionStderr() bool {
	if o != nil && o.ActionStderr != nil {
		return true
	}

	return false
}

// SetActionStderr gets a reference to the given string and assigns it to the ActionStderr field.
func (o *InstanceStatusTron) SetActionStderr(v string) {
	o.ActionStderr = &v
}

// GetActionStdout returns the ActionStdout field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetActionStdout() string {
	if o == nil || o.ActionStdout == nil {
		var ret string
		return ret
	}
	return *o.ActionStdout
}

// GetActionStdoutOk returns a tuple with the ActionStdout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetActionStdoutOk() (*string, bool) {
	if o == nil || o.ActionStdout == nil {
		return nil, false
	}
	return o.ActionStdout, true
}

// HasActionStdout returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasActionStdout() bool {
	if o != nil && o.ActionStdout != nil {
		return true
	}

	return false
}

// SetActionStdout gets a reference to the given string and assigns it to the ActionStdout field.
func (o *InstanceStatusTron) SetActionStdout(v string) {
	o.ActionStdout = &v
}

// GetJobName returns the JobName field value
func (o *InstanceStatusTron) GetJobName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.JobName
}

// GetJobNameOk returns a tuple with the JobName field value
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetJobNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.JobName, true
}

// SetJobName sets field value
func (o *InstanceStatusTron) SetJobName(v string) {
	o.JobName = v
}

// GetJobSchedule returns the JobSchedule field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetJobSchedule() string {
	if o == nil || o.JobSchedule == nil {
		var ret string
		return ret
	}
	return *o.JobSchedule
}

// GetJobScheduleOk returns a tuple with the JobSchedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetJobScheduleOk() (*string, bool) {
	if o == nil || o.JobSchedule == nil {
		return nil, false
	}
	return o.JobSchedule, true
}

// HasJobSchedule returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasJobSchedule() bool {
	if o != nil && o.JobSchedule != nil {
		return true
	}

	return false
}

// SetJobSchedule gets a reference to the given string and assigns it to the JobSchedule field.
func (o *InstanceStatusTron) SetJobSchedule(v string) {
	o.JobSchedule = &v
}

// GetJobStatus returns the JobStatus field value if set, zero value otherwise.
func (o *InstanceStatusTron) GetJobStatus() string {
	if o == nil || o.JobStatus == nil {
		var ret string
		return ret
	}
	return *o.JobStatus
}

// GetJobStatusOk returns a tuple with the JobStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetJobStatusOk() (*string, bool) {
	if o == nil || o.JobStatus == nil {
		return nil, false
	}
	return o.JobStatus, true
}

// HasJobStatus returns a boolean if a field has been set.
func (o *InstanceStatusTron) HasJobStatus() bool {
	if o != nil && o.JobStatus != nil {
		return true
	}

	return false
}

// SetJobStatus gets a reference to the given string and assigns it to the JobStatus field.
func (o *InstanceStatusTron) SetJobStatus(v string) {
	o.JobStatus = &v
}

// GetJobUrl returns the JobUrl field value
func (o *InstanceStatusTron) GetJobUrl() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.JobUrl
}

// GetJobUrlOk returns a tuple with the JobUrl field value
// and a boolean to check if the value has been set.
func (o *InstanceStatusTron) GetJobUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.JobUrl, true
}

// SetJobUrl sets field value
func (o *InstanceStatusTron) SetJobUrl(v string) {
	o.JobUrl = v
}

func (o InstanceStatusTron) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ActionCommand != nil {
		toSerialize["action_command"] = o.ActionCommand
	}
	if o.ActionName != nil {
		toSerialize["action_name"] = o.ActionName
	}
	if o.ActionRawCommand != nil {
		toSerialize["action_raw_command"] = o.ActionRawCommand
	}
	if o.ActionStartTime != nil {
		toSerialize["action_start_time"] = o.ActionStartTime
	}
	if o.ActionState != nil {
		toSerialize["action_state"] = o.ActionState
	}
	if o.ActionStderr != nil {
		toSerialize["action_stderr"] = o.ActionStderr
	}
	if o.ActionStdout != nil {
		toSerialize["action_stdout"] = o.ActionStdout
	}
	if true {
		toSerialize["job_name"] = o.JobName
	}
	if o.JobSchedule != nil {
		toSerialize["job_schedule"] = o.JobSchedule
	}
	if o.JobStatus != nil {
		toSerialize["job_status"] = o.JobStatus
	}
	if true {
		toSerialize["job_url"] = o.JobUrl
	}
	return json.Marshal(toSerialize)
}

type NullableInstanceStatusTron struct {
	value *InstanceStatusTron
	isSet bool
}

func (v NullableInstanceStatusTron) Get() *InstanceStatusTron {
	return v.value
}

func (v *NullableInstanceStatusTron) Set(val *InstanceStatusTron) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceStatusTron) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceStatusTron) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceStatusTron(val *InstanceStatusTron) *NullableInstanceStatusTron {
	return &NullableInstanceStatusTron{value: val, isSet: true}
}

func (v NullableInstanceStatusTron) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceStatusTron) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


