/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package paastaapi

import (
	"encoding/json"
)

// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	DesiredInstances *int32 `json:"desired_instances,omitempty"`
}

// NewInlineResponse2002 instantiates a new InlineResponse2002 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2002() *InlineResponse2002 {
	this := InlineResponse2002{}
	return &this
}

// NewInlineResponse2002WithDefaults instantiates a new InlineResponse2002 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2002WithDefaults() *InlineResponse2002 {
	this := InlineResponse2002{}
	return &this
}

// GetDesiredInstances returns the DesiredInstances field value if set, zero value otherwise.
func (o *InlineResponse2002) GetDesiredInstances() int32 {
	if o == nil || o.DesiredInstances == nil {
		var ret int32
		return ret
	}
	return *o.DesiredInstances
}

// GetDesiredInstancesOk returns a tuple with the DesiredInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetDesiredInstancesOk() (*int32, bool) {
	if o == nil || o.DesiredInstances == nil {
		return nil, false
	}
	return o.DesiredInstances, true
}

// HasDesiredInstances returns a boolean if a field has been set.
func (o *InlineResponse2002) HasDesiredInstances() bool {
	if o != nil && o.DesiredInstances != nil {
		return true
	}

	return false
}

// SetDesiredInstances gets a reference to the given int32 and assigns it to the DesiredInstances field.
func (o *InlineResponse2002) SetDesiredInstances(v int32) {
	o.DesiredInstances = &v
}

func (o InlineResponse2002) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DesiredInstances != nil {
		toSerialize["desired_instances"] = o.DesiredInstances
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2002 struct {
	value *InlineResponse2002
	isSet bool
}

func (v NullableInlineResponse2002) Get() *InlineResponse2002 {
	return v.value
}

func (v *NullableInlineResponse2002) Set(val *InlineResponse2002) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2002) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2002) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2002(val *InlineResponse2002) *NullableInlineResponse2002 {
	return &NullableInlineResponse2002{value: val, isSet: true}
}

func (v NullableInlineResponse2002) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2002) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


