/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paastaapi

import (
	"encoding/json"
)

// KubernetesPodEvent struct for KubernetesPodEvent
type KubernetesPodEvent struct {
	Message *string `json:"message,omitempty"`
	TimeStamp *string `json:"timeStamp,omitempty"`
}

// NewKubernetesPodEvent instantiates a new KubernetesPodEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubernetesPodEvent() *KubernetesPodEvent {
	this := KubernetesPodEvent{}
	return &this
}

// NewKubernetesPodEventWithDefaults instantiates a new KubernetesPodEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubernetesPodEventWithDefaults() *KubernetesPodEvent {
	this := KubernetesPodEvent{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *KubernetesPodEvent) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesPodEvent) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *KubernetesPodEvent) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *KubernetesPodEvent) SetMessage(v string) {
	o.Message = &v
}

// GetTimeStamp returns the TimeStamp field value if set, zero value otherwise.
func (o *KubernetesPodEvent) GetTimeStamp() string {
	if o == nil || o.TimeStamp == nil {
		var ret string
		return ret
	}
	return *o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesPodEvent) GetTimeStampOk() (*string, bool) {
	if o == nil || o.TimeStamp == nil {
		return nil, false
	}
	return o.TimeStamp, true
}

// HasTimeStamp returns a boolean if a field has been set.
func (o *KubernetesPodEvent) HasTimeStamp() bool {
	if o != nil && o.TimeStamp != nil {
		return true
	}

	return false
}

// SetTimeStamp gets a reference to the given string and assigns it to the TimeStamp field.
func (o *KubernetesPodEvent) SetTimeStamp(v string) {
	o.TimeStamp = &v
}

func (o KubernetesPodEvent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.TimeStamp != nil {
		toSerialize["timeStamp"] = o.TimeStamp
	}
	return json.Marshal(toSerialize)
}

type NullableKubernetesPodEvent struct {
	value *KubernetesPodEvent
	isSet bool
}

func (v NullableKubernetesPodEvent) Get() *KubernetesPodEvent {
	return v.value
}

func (v *NullableKubernetesPodEvent) Set(val *KubernetesPodEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableKubernetesPodEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableKubernetesPodEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubernetesPodEvent(val *KubernetesPodEvent) *NullableKubernetesPodEvent {
	return &NullableKubernetesPodEvent{value: val, isSet: true}
}

func (v NullableKubernetesPodEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubernetesPodEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


