/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paastaapi

import (
	"encoding/json"
)

// EnvoyBackend struct for EnvoyBackend
type EnvoyBackend struct {
	// Address of the host on which the backend is running
	Address *string `json:"address,omitempty"`
	// Status of the backend in Envoy as reported by the EDS
	EdsHealthStatus *string `json:"eds_health_status,omitempty"`
	// Whether this backend has an associated task running
	HasAssociatedTask *bool `json:"has_associated_task,omitempty"`
	// Name of the host on which the backend is running
	Hostname *string `json:"hostname,omitempty"`
	// Port number on which the backend responds
	PortValue *int32 `json:"port_value,omitempty"`
	// The weight of this backend in the cluster
	Weight *int32 `json:"weight,omitempty"`
}

// NewEnvoyBackend instantiates a new EnvoyBackend object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvoyBackend() *EnvoyBackend {
	this := EnvoyBackend{}
	return &this
}

// NewEnvoyBackendWithDefaults instantiates a new EnvoyBackend object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvoyBackendWithDefaults() *EnvoyBackend {
	this := EnvoyBackend{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *EnvoyBackend) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoyBackend) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *EnvoyBackend) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *EnvoyBackend) SetAddress(v string) {
	o.Address = &v
}

// GetEdsHealthStatus returns the EdsHealthStatus field value if set, zero value otherwise.
func (o *EnvoyBackend) GetEdsHealthStatus() string {
	if o == nil || o.EdsHealthStatus == nil {
		var ret string
		return ret
	}
	return *o.EdsHealthStatus
}

// GetEdsHealthStatusOk returns a tuple with the EdsHealthStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoyBackend) GetEdsHealthStatusOk() (*string, bool) {
	if o == nil || o.EdsHealthStatus == nil {
		return nil, false
	}
	return o.EdsHealthStatus, true
}

// HasEdsHealthStatus returns a boolean if a field has been set.
func (o *EnvoyBackend) HasEdsHealthStatus() bool {
	if o != nil && o.EdsHealthStatus != nil {
		return true
	}

	return false
}

// SetEdsHealthStatus gets a reference to the given string and assigns it to the EdsHealthStatus field.
func (o *EnvoyBackend) SetEdsHealthStatus(v string) {
	o.EdsHealthStatus = &v
}

// GetHasAssociatedTask returns the HasAssociatedTask field value if set, zero value otherwise.
func (o *EnvoyBackend) GetHasAssociatedTask() bool {
	if o == nil || o.HasAssociatedTask == nil {
		var ret bool
		return ret
	}
	return *o.HasAssociatedTask
}

// GetHasAssociatedTaskOk returns a tuple with the HasAssociatedTask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoyBackend) GetHasAssociatedTaskOk() (*bool, bool) {
	if o == nil || o.HasAssociatedTask == nil {
		return nil, false
	}
	return o.HasAssociatedTask, true
}

// HasHasAssociatedTask returns a boolean if a field has been set.
func (o *EnvoyBackend) HasHasAssociatedTask() bool {
	if o != nil && o.HasAssociatedTask != nil {
		return true
	}

	return false
}

// SetHasAssociatedTask gets a reference to the given bool and assigns it to the HasAssociatedTask field.
func (o *EnvoyBackend) SetHasAssociatedTask(v bool) {
	o.HasAssociatedTask = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *EnvoyBackend) GetHostname() string {
	if o == nil || o.Hostname == nil {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoyBackend) GetHostnameOk() (*string, bool) {
	if o == nil || o.Hostname == nil {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *EnvoyBackend) HasHostname() bool {
	if o != nil && o.Hostname != nil {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *EnvoyBackend) SetHostname(v string) {
	o.Hostname = &v
}

// GetPortValue returns the PortValue field value if set, zero value otherwise.
func (o *EnvoyBackend) GetPortValue() int32 {
	if o == nil || o.PortValue == nil {
		var ret int32
		return ret
	}
	return *o.PortValue
}

// GetPortValueOk returns a tuple with the PortValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoyBackend) GetPortValueOk() (*int32, bool) {
	if o == nil || o.PortValue == nil {
		return nil, false
	}
	return o.PortValue, true
}

// HasPortValue returns a boolean if a field has been set.
func (o *EnvoyBackend) HasPortValue() bool {
	if o != nil && o.PortValue != nil {
		return true
	}

	return false
}

// SetPortValue gets a reference to the given int32 and assigns it to the PortValue field.
func (o *EnvoyBackend) SetPortValue(v int32) {
	o.PortValue = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *EnvoyBackend) GetWeight() int32 {
	if o == nil || o.Weight == nil {
		var ret int32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoyBackend) GetWeightOk() (*int32, bool) {
	if o == nil || o.Weight == nil {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *EnvoyBackend) HasWeight() bool {
	if o != nil && o.Weight != nil {
		return true
	}

	return false
}

// SetWeight gets a reference to the given int32 and assigns it to the Weight field.
func (o *EnvoyBackend) SetWeight(v int32) {
	o.Weight = &v
}

func (o EnvoyBackend) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.EdsHealthStatus != nil {
		toSerialize["eds_health_status"] = o.EdsHealthStatus
	}
	if o.HasAssociatedTask != nil {
		toSerialize["has_associated_task"] = o.HasAssociatedTask
	}
	if o.Hostname != nil {
		toSerialize["hostname"] = o.Hostname
	}
	if o.PortValue != nil {
		toSerialize["port_value"] = o.PortValue
	}
	if o.Weight != nil {
		toSerialize["weight"] = o.Weight
	}
	return json.Marshal(toSerialize)
}

type NullableEnvoyBackend struct {
	value *EnvoyBackend
	isSet bool
}

func (v NullableEnvoyBackend) Get() *EnvoyBackend {
	return v.value
}

func (v *NullableEnvoyBackend) Set(val *EnvoyBackend) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvoyBackend) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvoyBackend) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvoyBackend(val *EnvoyBackend) *NullableEnvoyBackend {
	return &NullableEnvoyBackend{value: val, isSet: true}
}

func (v NullableEnvoyBackend) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvoyBackend) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


