/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paastaapi

import (
	"encoding/json"
)

// MetaStatus Result of `paasta metastatus` command
type MetaStatus struct {
	// Exit code from `paasta metastatus` command
	ExitCode *int32 `json:"exit_code,omitempty"`
	// Output from `paasta metastatus` command
	Output *string `json:"output,omitempty"`
}

// NewMetaStatus instantiates a new MetaStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaStatus() *MetaStatus {
	this := MetaStatus{}
	return &this
}

// NewMetaStatusWithDefaults instantiates a new MetaStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaStatusWithDefaults() *MetaStatus {
	this := MetaStatus{}
	return &this
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise.
func (o *MetaStatus) GetExitCode() int32 {
	if o == nil || o.ExitCode == nil {
		var ret int32
		return ret
	}
	return *o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaStatus) GetExitCodeOk() (*int32, bool) {
	if o == nil || o.ExitCode == nil {
		return nil, false
	}
	return o.ExitCode, true
}

// HasExitCode returns a boolean if a field has been set.
func (o *MetaStatus) HasExitCode() bool {
	if o != nil && o.ExitCode != nil {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given int32 and assigns it to the ExitCode field.
func (o *MetaStatus) SetExitCode(v int32) {
	o.ExitCode = &v
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (o *MetaStatus) GetOutput() string {
	if o == nil || o.Output == nil {
		var ret string
		return ret
	}
	return *o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaStatus) GetOutputOk() (*string, bool) {
	if o == nil || o.Output == nil {
		return nil, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *MetaStatus) HasOutput() bool {
	if o != nil && o.Output != nil {
		return true
	}

	return false
}

// SetOutput gets a reference to the given string and assigns it to the Output field.
func (o *MetaStatus) SetOutput(v string) {
	o.Output = &v
}

func (o MetaStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExitCode != nil {
		toSerialize["exit_code"] = o.ExitCode
	}
	if o.Output != nil {
		toSerialize["output"] = o.Output
	}
	return json.Marshal(toSerialize)
}

type NullableMetaStatus struct {
	value *MetaStatus
	isSet bool
}

func (v NullableMetaStatus) Get() *MetaStatus {
	return v.value
}

func (v *NullableMetaStatus) Set(val *MetaStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaStatus(val *MetaStatus) *NullableMetaStatus {
	return &NullableMetaStatus{value: val, isSet: true}
}

func (v NullableMetaStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


