/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package paastaapi

import (
	"encoding/json"
)

// InstanceStatusKafkacluster Nullable KafkaCluster instance status and metadata
type InstanceStatusKafkacluster struct {
	// Kafka instance metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	// Kafka instance status
	Status *map[string]interface{} `json:"status,omitempty"`
}

// NewInstanceStatusKafkacluster instantiates a new InstanceStatusKafkacluster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceStatusKafkacluster() *InstanceStatusKafkacluster {
	this := InstanceStatusKafkacluster{}
	return &this
}

// NewInstanceStatusKafkaclusterWithDefaults instantiates a new InstanceStatusKafkacluster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceStatusKafkaclusterWithDefaults() *InstanceStatusKafkacluster {
	this := InstanceStatusKafkacluster{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *InstanceStatusKafkacluster) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusKafkacluster) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *InstanceStatusKafkacluster) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *InstanceStatusKafkacluster) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InstanceStatusKafkacluster) GetStatus() map[string]interface{} {
	if o == nil || o.Status == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusKafkacluster) GetStatusOk() (*map[string]interface{}, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InstanceStatusKafkacluster) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given map[string]interface{} and assigns it to the Status field.
func (o *InstanceStatusKafkacluster) SetStatus(v map[string]interface{}) {
	o.Status = &v
}

func (o InstanceStatusKafkacluster) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableInstanceStatusKafkacluster struct {
	value *InstanceStatusKafkacluster
	isSet bool
}

func (v NullableInstanceStatusKafkacluster) Get() *InstanceStatusKafkacluster {
	return v.value
}

func (v *NullableInstanceStatusKafkacluster) Set(val *InstanceStatusKafkacluster) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceStatusKafkacluster) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceStatusKafkacluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceStatusKafkacluster(val *InstanceStatusKafkacluster) *NullableInstanceStatusKafkacluster {
	return &NullableInstanceStatusKafkacluster{value: val, isSet: true}
}

func (v NullableInstanceStatusKafkacluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceStatusKafkacluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


