/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package paastaapi

import (
	"encoding/json"
)

// MarathonDashboardItem Marathon service, instance, and shard url
type MarathonDashboardItem struct {
	// Instance name
	Instance *string `json:"instance,omitempty"`
	// Service name
	Service *string `json:"service,omitempty"`
	// Marathon Shard URL
	ShardUrl *string `json:"shard_url,omitempty"`
}

// NewMarathonDashboardItem instantiates a new MarathonDashboardItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarathonDashboardItem() *MarathonDashboardItem {
	this := MarathonDashboardItem{}
	return &this
}

// NewMarathonDashboardItemWithDefaults instantiates a new MarathonDashboardItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarathonDashboardItemWithDefaults() *MarathonDashboardItem {
	this := MarathonDashboardItem{}
	return &this
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *MarathonDashboardItem) GetInstance() string {
	if o == nil || o.Instance == nil {
		var ret string
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarathonDashboardItem) GetInstanceOk() (*string, bool) {
	if o == nil || o.Instance == nil {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *MarathonDashboardItem) HasInstance() bool {
	if o != nil && o.Instance != nil {
		return true
	}

	return false
}

// SetInstance gets a reference to the given string and assigns it to the Instance field.
func (o *MarathonDashboardItem) SetInstance(v string) {
	o.Instance = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *MarathonDashboardItem) GetService() string {
	if o == nil || o.Service == nil {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarathonDashboardItem) GetServiceOk() (*string, bool) {
	if o == nil || o.Service == nil {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *MarathonDashboardItem) HasService() bool {
	if o != nil && o.Service != nil {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *MarathonDashboardItem) SetService(v string) {
	o.Service = &v
}

// GetShardUrl returns the ShardUrl field value if set, zero value otherwise.
func (o *MarathonDashboardItem) GetShardUrl() string {
	if o == nil || o.ShardUrl == nil {
		var ret string
		return ret
	}
	return *o.ShardUrl
}

// GetShardUrlOk returns a tuple with the ShardUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarathonDashboardItem) GetShardUrlOk() (*string, bool) {
	if o == nil || o.ShardUrl == nil {
		return nil, false
	}
	return o.ShardUrl, true
}

// HasShardUrl returns a boolean if a field has been set.
func (o *MarathonDashboardItem) HasShardUrl() bool {
	if o != nil && o.ShardUrl != nil {
		return true
	}

	return false
}

// SetShardUrl gets a reference to the given string and assigns it to the ShardUrl field.
func (o *MarathonDashboardItem) SetShardUrl(v string) {
	o.ShardUrl = &v
}

func (o MarathonDashboardItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Instance != nil {
		toSerialize["instance"] = o.Instance
	}
	if o.Service != nil {
		toSerialize["service"] = o.Service
	}
	if o.ShardUrl != nil {
		toSerialize["shard_url"] = o.ShardUrl
	}
	return json.Marshal(toSerialize)
}

type NullableMarathonDashboardItem struct {
	value *MarathonDashboardItem
	isSet bool
}

func (v NullableMarathonDashboardItem) Get() *MarathonDashboardItem {
	return v.value
}

func (v *NullableMarathonDashboardItem) Set(val *MarathonDashboardItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMarathonDashboardItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMarathonDashboardItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarathonDashboardItem(val *MarathonDashboardItem) *NullableMarathonDashboardItem {
	return &NullableMarathonDashboardItem{value: val, isSet: true}
}

func (v NullableMarathonDashboardItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarathonDashboardItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


