/*
 * Paasta API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package paastaapi

import (
	"encoding/json"
)

// InstanceStatusKubernetesAutoscalingStatus HPA associated to this app
type InstanceStatusKubernetesAutoscalingStatus struct {
	// desired number of _instances as calculated by HPA
	DesiredReplicas *int32 `json:"desired_replicas,omitempty"`
	// timestamp of last autoscale
	LastScaleTime *string `json:"last_scale_time,omitempty"`
	// min_instances as specified in yelpsoa_configs
	MaxInstances *int32 `json:"max_instances,omitempty"`
	// Current metrics
	Metrics *[]HPAMetric `json:"metrics,omitempty"`
	// min_instances as specified in yelpsoa_configs
	MinInstances *int32 `json:"min_instances,omitempty"`
}

// NewInstanceStatusKubernetesAutoscalingStatus instantiates a new InstanceStatusKubernetesAutoscalingStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceStatusKubernetesAutoscalingStatus() *InstanceStatusKubernetesAutoscalingStatus {
	this := InstanceStatusKubernetesAutoscalingStatus{}
	return &this
}

// NewInstanceStatusKubernetesAutoscalingStatusWithDefaults instantiates a new InstanceStatusKubernetesAutoscalingStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceStatusKubernetesAutoscalingStatusWithDefaults() *InstanceStatusKubernetesAutoscalingStatus {
	this := InstanceStatusKubernetesAutoscalingStatus{}
	return &this
}

// GetDesiredReplicas returns the DesiredReplicas field value if set, zero value otherwise.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetDesiredReplicas() int32 {
	if o == nil || o.DesiredReplicas == nil {
		var ret int32
		return ret
	}
	return *o.DesiredReplicas
}

// GetDesiredReplicasOk returns a tuple with the DesiredReplicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetDesiredReplicasOk() (*int32, bool) {
	if o == nil || o.DesiredReplicas == nil {
		return nil, false
	}
	return o.DesiredReplicas, true
}

// HasDesiredReplicas returns a boolean if a field has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) HasDesiredReplicas() bool {
	if o != nil && o.DesiredReplicas != nil {
		return true
	}

	return false
}

// SetDesiredReplicas gets a reference to the given int32 and assigns it to the DesiredReplicas field.
func (o *InstanceStatusKubernetesAutoscalingStatus) SetDesiredReplicas(v int32) {
	o.DesiredReplicas = &v
}

// GetLastScaleTime returns the LastScaleTime field value if set, zero value otherwise.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetLastScaleTime() string {
	if o == nil || o.LastScaleTime == nil {
		var ret string
		return ret
	}
	return *o.LastScaleTime
}

// GetLastScaleTimeOk returns a tuple with the LastScaleTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetLastScaleTimeOk() (*string, bool) {
	if o == nil || o.LastScaleTime == nil {
		return nil, false
	}
	return o.LastScaleTime, true
}

// HasLastScaleTime returns a boolean if a field has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) HasLastScaleTime() bool {
	if o != nil && o.LastScaleTime != nil {
		return true
	}

	return false
}

// SetLastScaleTime gets a reference to the given string and assigns it to the LastScaleTime field.
func (o *InstanceStatusKubernetesAutoscalingStatus) SetLastScaleTime(v string) {
	o.LastScaleTime = &v
}

// GetMaxInstances returns the MaxInstances field value if set, zero value otherwise.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetMaxInstances() int32 {
	if o == nil || o.MaxInstances == nil {
		var ret int32
		return ret
	}
	return *o.MaxInstances
}

// GetMaxInstancesOk returns a tuple with the MaxInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetMaxInstancesOk() (*int32, bool) {
	if o == nil || o.MaxInstances == nil {
		return nil, false
	}
	return o.MaxInstances, true
}

// HasMaxInstances returns a boolean if a field has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) HasMaxInstances() bool {
	if o != nil && o.MaxInstances != nil {
		return true
	}

	return false
}

// SetMaxInstances gets a reference to the given int32 and assigns it to the MaxInstances field.
func (o *InstanceStatusKubernetesAutoscalingStatus) SetMaxInstances(v int32) {
	o.MaxInstances = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetMetrics() []HPAMetric {
	if o == nil || o.Metrics == nil {
		var ret []HPAMetric
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetMetricsOk() (*[]HPAMetric, bool) {
	if o == nil || o.Metrics == nil {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) HasMetrics() bool {
	if o != nil && o.Metrics != nil {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given []HPAMetric and assigns it to the Metrics field.
func (o *InstanceStatusKubernetesAutoscalingStatus) SetMetrics(v []HPAMetric) {
	o.Metrics = &v
}

// GetMinInstances returns the MinInstances field value if set, zero value otherwise.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetMinInstances() int32 {
	if o == nil || o.MinInstances == nil {
		var ret int32
		return ret
	}
	return *o.MinInstances
}

// GetMinInstancesOk returns a tuple with the MinInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) GetMinInstancesOk() (*int32, bool) {
	if o == nil || o.MinInstances == nil {
		return nil, false
	}
	return o.MinInstances, true
}

// HasMinInstances returns a boolean if a field has been set.
func (o *InstanceStatusKubernetesAutoscalingStatus) HasMinInstances() bool {
	if o != nil && o.MinInstances != nil {
		return true
	}

	return false
}

// SetMinInstances gets a reference to the given int32 and assigns it to the MinInstances field.
func (o *InstanceStatusKubernetesAutoscalingStatus) SetMinInstances(v int32) {
	o.MinInstances = &v
}

func (o InstanceStatusKubernetesAutoscalingStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DesiredReplicas != nil {
		toSerialize["desired_replicas"] = o.DesiredReplicas
	}
	if o.LastScaleTime != nil {
		toSerialize["last_scale_time"] = o.LastScaleTime
	}
	if o.MaxInstances != nil {
		toSerialize["max_instances"] = o.MaxInstances
	}
	if o.Metrics != nil {
		toSerialize["metrics"] = o.Metrics
	}
	if o.MinInstances != nil {
		toSerialize["min_instances"] = o.MinInstances
	}
	return json.Marshal(toSerialize)
}

type NullableInstanceStatusKubernetesAutoscalingStatus struct {
	value *InstanceStatusKubernetesAutoscalingStatus
	isSet bool
}

func (v NullableInstanceStatusKubernetesAutoscalingStatus) Get() *InstanceStatusKubernetesAutoscalingStatus {
	return v.value
}

func (v *NullableInstanceStatusKubernetesAutoscalingStatus) Set(val *InstanceStatusKubernetesAutoscalingStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceStatusKubernetesAutoscalingStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceStatusKubernetesAutoscalingStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceStatusKubernetesAutoscalingStatus(val *InstanceStatusKubernetesAutoscalingStatus) *NullableInstanceStatusKubernetesAutoscalingStatus {
	return &NullableInstanceStatusKubernetesAutoscalingStatus{value: val, isSet: true}
}

func (v NullableInstanceStatusKubernetesAutoscalingStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceStatusKubernetesAutoscalingStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


